#############################################################################
# Makefile for building: ai
# Generated by qmake (3.1) (Qt 6.4.2)
# Project:  ai.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile ai.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DMAVLINK_ALIGNED_FIELDS=1 -DMAVLINK_COMMAND_24BIT=1 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -Wno-address-of-packed-member -Wno-pedantic -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/include/libcamera -I/usr/local/include/opencv4 -Iinclude/Output -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I. -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ai1.0.0
DISTDIR = /home/pi5/shared_folder/aiPlatform/.tmp/ai1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/aarch64-linux-gnu
LIBS          = $(SUBLIBS) -L/usr/lib -lcamera-base -lpisp -lcamera -L/usr/local/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_dnn -lopencv_tracking -lopencv_video -lopencv_objdetect -lopencv_ml -lopencv_gapi -lstdc++fs -lspdlog -lfmt /usr/lib/aarch64-linux-gnu/libQt6Widgets.so /usr/lib/aarch64-linux-gnu/libQt6Gui.so /usr/lib/aarch64-linux-gnu/libGLX.so /usr/lib/aarch64-linux-gnu/libOpenGL.so /usr/lib/aarch64-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/application.cpp \
		src/mainwindow.cpp \
		src/visualizer.cpp \
		src/failure_handler.cpp \
		src/camera_handler.cpp \
		src/video_handler.cpp \
		src/config_utils.cpp \
		src/control_unit.cpp \
		src/frame_buffer_manager.cpp \
		src/model.cpp \
		src/model_manager.cpp \
		src/resource_monitor.cpp \
		src/tracking/siamfc_pp_tracker.cpp \
		src/tracking/vittracker.cpp \
		src/tracking/csrt_tracker.cpp \
		src/tracker_manager.cpp \
		src/detection_manager.cpp \
		src/detection/yolo_detector.cpp \
		src/detection/color_detector.cpp \
		src/mavlink.cpp \
		src/navigation_unit.cpp \
		src/logger.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		application.o \
		mainwindow.o \
		visualizer.o \
		failure_handler.o \
		camera_handler.o \
		video_handler.o \
		config_utils.o \
		control_unit.o \
		frame_buffer_manager.o \
		model.o \
		model_manager.o \
		resource_monitor.o \
		siamfc_pp_tracker.o \
		vittracker.o \
		csrt_tracker.o \
		tracker_manager.o \
		detection_manager.o \
		yolo_detector.o \
		color_detector.o \
		mavlink.o \
		navigation_unit.o \
		logger.o \
		moc_mainwindow.o
DIST          = /usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/lex.prf \
		ai.pro include/application.h \
		include/mainwindow.h \
		include/visualizer.h \
		include/failure_handler.h \
		include/camera_handler.h \
		include/video_handler.h \
		include/config_utils.h \
		include/control_unit.h \
		include/frame_buffer_manager.h \
		include/model.h \
		include/model_manager.h \
		include/resource_monitor.h \
		include/tracking/siamfc_pp_tracker.h \
		include/tracking/vittracker.h \
		include/tracking/csrt_tracker.h \
		include/tracker_interface.h \
		include/tracker_manager.h \
		include/detection_manager.h \
		include/detection/yolo_detector.h \
		include/detection/color_detector.h \
		include/frame_pool.h \
		include/mavlink.h \
		include/navigation_unit.h \
		include/logger.h src/main.cpp \
		src/application.cpp \
		src/mainwindow.cpp \
		src/visualizer.cpp \
		src/failure_handler.cpp \
		src/camera_handler.cpp \
		src/video_handler.cpp \
		src/config_utils.cpp \
		src/control_unit.cpp \
		src/frame_buffer_manager.cpp \
		src/model.cpp \
		src/model_manager.cpp \
		src/resource_monitor.cpp \
		src/tracking/siamfc_pp_tracker.cpp \
		src/tracking/vittracker.cpp \
		src/tracking/csrt_tracker.cpp \
		src/tracker_manager.cpp \
		src/detection_manager.cpp \
		src/detection/yolo_detector.cpp \
		src/detection/color_detector.cpp \
		src/mavlink.cpp \
		src/navigation_unit.cpp \
		src/logger.cpp
QMAKE_TARGET  = ai
DESTDIR       = 
TARGET        = ai


first: all
####### Build rules

ai:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ai.pro /usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/lex.prf \
		ai.pro \
		/usr/lib/aarch64-linux-gnu/libQt6Widgets.prl \
		/usr/lib/aarch64-linux-gnu/libQt6Gui.prl \
		/usr/lib/aarch64-linux-gnu/libQt6Core.prl
	$(QMAKE) -o Makefile ai.pro
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_post.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/moc.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/uic.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/lex.prf:
ai.pro:
/usr/lib/aarch64-linux-gnu/libQt6Widgets.prl:
/usr/lib/aarch64-linux-gnu/libQt6Gui.prl:
/usr/lib/aarch64-linux-gnu/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ai.pro

qmake_all: FORCE


all: Makefile ai

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/application.h include/mainwindow.h include/visualizer.h include/failure_handler.h include/camera_handler.h include/video_handler.h include/config_utils.h include/control_unit.h include/frame_buffer_manager.h include/model.h include/model_manager.h include/resource_monitor.h include/tracking/siamfc_pp_tracker.h include/tracking/vittracker.h include/tracking/csrt_tracker.h include/tracker_interface.h include/tracker_manager.h include/detection_manager.h include/detection/yolo_detector.h include/detection/color_detector.h include/frame_pool.h include/mavlink.h include/navigation_unit.h include/logger.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/application.cpp src/mainwindow.cpp src/visualizer.cpp src/failure_handler.cpp src/camera_handler.cpp src/video_handler.cpp src/config_utils.cpp src/control_unit.cpp src/frame_buffer_manager.cpp src/model.cpp src/model_manager.cpp src/resource_monitor.cpp src/tracking/siamfc_pp_tracker.cpp src/tracking/vittracker.cpp src/tracking/csrt_tracker.cpp src/tracker_manager.cpp src/detection_manager.cpp src/detection/yolo_detector.cpp src/detection/color_detector.cpp src/mavlink.cpp src/navigation_unit.cpp src/logger.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -Wno-address-of-packed-member -Wno-pedantic -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: include/mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/pi5/shared_folder/aiPlatform/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/pi5/shared_folder/aiPlatform -I/usr/include/libcamera -I/usr/local/include/opencv4 -I/home/pi5/shared_folder/aiPlatform/include/Output -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/12 -I/usr/include/aarch64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/aarch64-linux-gnu/12/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include include/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp include/mainwindow.h \
		include/application.h \
		include/camera_handler.h \
		include/frame_buffer_manager.h \
		include/control_unit.h \
		include/tracker_interface.h \
		include/video_handler.h \
		include/model_manager.h \
		include/model.h \
		include/tracker_manager.h \
		include/visualizer.h \
		include/navigation_unit.h \
		include/failure_handler.h \
		include/mavlink.h \
		include/Output/common/mavlink.h \
		include/Output/common/version.h \
		include/Output/common/common.h \
		include/Output/protocol.h \
		include/Output/mavlink_types.h \
		include/Output/mavlink_helpers.h \
		include/Output/checksum.h \
		include/Output/mavlink_conversions.h \
		include/Output/mavlink_sha256.h \
		include/Output/common/mavlink_msg_sys_status.h \
		include/Output/common/mavlink_msg_system_time.h \
		include/Output/common/mavlink_msg_ping.h \
		include/Output/common/mavlink_msg_change_operator_control.h \
		include/Output/common/mavlink_msg_change_operator_control_ack.h \
		include/Output/common/mavlink_msg_auth_key.h \
		include/Output/common/mavlink_msg_link_node_status.h \
		include/Output/common/mavlink_msg_set_mode.h \
		include/Output/common/mavlink_msg_param_request_read.h \
		include/Output/common/mavlink_msg_param_request_list.h \
		include/Output/common/mavlink_msg_param_value.h \
		include/Output/common/mavlink_msg_param_set.h \
		include/Output/common/mavlink_msg_gps_raw_int.h \
		include/Output/common/mavlink_msg_gps_status.h \
		include/Output/common/mavlink_msg_scaled_imu.h \
		include/Output/common/mavlink_msg_raw_imu.h \
		include/Output/common/mavlink_msg_raw_pressure.h \
		include/Output/common/mavlink_msg_scaled_pressure.h \
		include/Output/common/mavlink_msg_attitude.h \
		include/Output/common/mavlink_msg_attitude_quaternion.h \
		include/Output/common/mavlink_msg_local_position_ned.h \
		include/Output/common/mavlink_msg_global_position_int.h \
		include/Output/common/mavlink_msg_rc_channels_scaled.h \
		include/Output/common/mavlink_msg_rc_channels_raw.h \
		include/Output/common/mavlink_msg_servo_output_raw.h \
		include/Output/common/mavlink_msg_mission_request_partial_list.h \
		include/Output/common/mavlink_msg_mission_write_partial_list.h \
		include/Output/common/mavlink_msg_mission_item.h \
		include/Output/common/mavlink_msg_mission_request.h \
		include/Output/common/mavlink_msg_mission_set_current.h \
		include/Output/common/mavlink_msg_mission_current.h \
		include/Output/common/mavlink_msg_mission_request_list.h \
		include/Output/common/mavlink_msg_mission_count.h \
		include/Output/common/mavlink_msg_mission_clear_all.h \
		include/Output/common/mavlink_msg_mission_item_reached.h \
		include/Output/common/mavlink_msg_mission_ack.h \
		include/Output/common/mavlink_msg_set_gps_global_origin.h \
		include/Output/common/mavlink_msg_gps_global_origin.h \
		include/Output/common/mavlink_msg_param_map_rc.h \
		include/Output/common/mavlink_msg_mission_request_int.h \
		include/Output/common/mavlink_msg_safety_set_allowed_area.h \
		include/Output/common/mavlink_msg_safety_allowed_area.h \
		include/Output/common/mavlink_msg_attitude_quaternion_cov.h \
		include/Output/common/mavlink_msg_nav_controller_output.h \
		include/Output/common/mavlink_msg_global_position_int_cov.h \
		include/Output/common/mavlink_msg_local_position_ned_cov.h \
		include/Output/common/mavlink_msg_rc_channels.h \
		include/Output/common/mavlink_msg_request_data_stream.h \
		include/Output/common/mavlink_msg_data_stream.h \
		include/Output/common/mavlink_msg_manual_control.h \
		include/Output/common/mavlink_msg_rc_channels_override.h \
		include/Output/common/mavlink_msg_mission_item_int.h \
		include/Output/common/mavlink_msg_vfr_hud.h \
		include/Output/common/mavlink_msg_command_int.h \
		include/Output/common/mavlink_msg_command_long.h \
		include/Output/common/mavlink_msg_command_ack.h \
		include/Output/common/mavlink_msg_command_cancel.h \
		include/Output/common/mavlink_msg_manual_setpoint.h \
		include/Output/common/mavlink_msg_set_attitude_target.h \
		include/Output/common/mavlink_msg_attitude_target.h \
		include/Output/common/mavlink_msg_set_position_target_local_ned.h \
		include/Output/common/mavlink_msg_position_target_local_ned.h \
		include/Output/common/mavlink_msg_set_position_target_global_int.h \
		include/Output/common/mavlink_msg_position_target_global_int.h \
		include/Output/common/mavlink_msg_local_position_ned_system_global_offset.h \
		include/Output/common/mavlink_msg_hil_state.h \
		include/Output/common/mavlink_msg_hil_controls.h \
		include/Output/common/mavlink_msg_hil_rc_inputs_raw.h \
		include/Output/common/mavlink_msg_hil_actuator_controls.h \
		include/Output/common/mavlink_msg_optical_flow.h \
		include/Output/common/mavlink_msg_global_vision_position_estimate.h \
		include/Output/common/mavlink_msg_vision_position_estimate.h \
		include/Output/common/mavlink_msg_vision_speed_estimate.h \
		include/Output/common/mavlink_msg_vicon_position_estimate.h \
		include/Output/common/mavlink_msg_highres_imu.h \
		include/Output/common/mavlink_msg_optical_flow_rad.h \
		include/Output/common/mavlink_msg_hil_sensor.h \
		include/Output/common/mavlink_msg_sim_state.h \
		include/Output/common/mavlink_msg_radio_status.h \
		include/Output/common/mavlink_msg_file_transfer_protocol.h \
		include/Output/common/mavlink_msg_timesync.h \
		include/Output/common/mavlink_msg_camera_trigger.h \
		include/Output/common/mavlink_msg_hil_gps.h \
		include/Output/common/mavlink_msg_hil_optical_flow.h \
		include/Output/common/mavlink_msg_hil_state_quaternion.h \
		include/Output/common/mavlink_msg_scaled_imu2.h \
		include/Output/common/mavlink_msg_log_request_list.h \
		include/Output/common/mavlink_msg_log_entry.h \
		include/Output/common/mavlink_msg_log_request_data.h \
		include/Output/common/mavlink_msg_log_data.h \
		include/Output/common/mavlink_msg_log_erase.h \
		include/Output/common/mavlink_msg_log_request_end.h \
		include/Output/common/mavlink_msg_gps_inject_data.h \
		include/Output/common/mavlink_msg_gps2_raw.h \
		include/Output/common/mavlink_msg_power_status.h \
		include/Output/common/mavlink_msg_serial_control.h \
		include/Output/common/mavlink_msg_gps_rtk.h \
		include/Output/common/mavlink_msg_gps2_rtk.h \
		include/Output/common/mavlink_msg_scaled_imu3.h \
		include/Output/common/mavlink_msg_data_transmission_handshake.h \
		include/Output/common/mavlink_msg_encapsulated_data.h \
		include/Output/common/mavlink_msg_distance_sensor.h \
		include/Output/common/mavlink_msg_terrain_request.h \
		include/Output/common/mavlink_msg_terrain_data.h \
		include/Output/common/mavlink_msg_terrain_check.h \
		include/Output/common/mavlink_msg_terrain_report.h \
		include/Output/common/mavlink_msg_scaled_pressure2.h \
		include/Output/common/mavlink_msg_att_pos_mocap.h \
		include/Output/common/mavlink_msg_set_actuator_control_target.h \
		include/Output/common/mavlink_msg_actuator_control_target.h \
		include/Output/common/mavlink_msg_altitude.h \
		include/Output/common/mavlink_msg_resource_request.h \
		include/Output/common/mavlink_msg_scaled_pressure3.h \
		include/Output/common/mavlink_msg_follow_target.h \
		include/Output/common/mavlink_msg_control_system_state.h \
		include/Output/common/mavlink_msg_battery_status.h \
		include/Output/common/mavlink_msg_autopilot_version.h \
		include/Output/common/mavlink_msg_landing_target.h \
		include/Output/common/mavlink_msg_fence_status.h \
		include/Output/common/mavlink_msg_mag_cal_report.h \
		include/Output/common/mavlink_msg_efi_status.h \
		include/Output/common/mavlink_msg_estimator_status.h \
		include/Output/common/mavlink_msg_wind_cov.h \
		include/Output/common/mavlink_msg_gps_input.h \
		include/Output/common/mavlink_msg_gps_rtcm_data.h \
		include/Output/common/mavlink_msg_high_latency.h \
		include/Output/common/mavlink_msg_high_latency2.h \
		include/Output/common/mavlink_msg_vibration.h \
		include/Output/common/mavlink_msg_home_position.h \
		include/Output/common/mavlink_msg_set_home_position.h \
		include/Output/common/mavlink_msg_message_interval.h \
		include/Output/common/mavlink_msg_extended_sys_state.h \
		include/Output/common/mavlink_msg_adsb_vehicle.h \
		include/Output/common/mavlink_msg_collision.h \
		include/Output/common/mavlink_msg_v2_extension.h \
		include/Output/common/mavlink_msg_memory_vect.h \
		include/Output/common/mavlink_msg_debug_vect.h \
		include/Output/common/mavlink_msg_named_value_float.h \
		include/Output/common/mavlink_msg_named_value_int.h \
		include/Output/common/mavlink_msg_statustext.h \
		include/Output/common/mavlink_msg_debug.h \
		include/Output/common/mavlink_msg_setup_signing.h \
		include/Output/common/mavlink_msg_button_change.h \
		include/Output/common/mavlink_msg_play_tune.h \
		include/Output/common/mavlink_msg_camera_information.h \
		include/Output/common/mavlink_msg_camera_settings.h \
		include/Output/common/mavlink_msg_storage_information.h \
		include/Output/common/mavlink_msg_camera_capture_status.h \
		include/Output/common/mavlink_msg_camera_image_captured.h \
		include/Output/common/mavlink_msg_flight_information.h \
		include/Output/common/mavlink_msg_mount_orientation.h \
		include/Output/common/mavlink_msg_logging_data.h \
		include/Output/common/mavlink_msg_logging_data_acked.h \
		include/Output/common/mavlink_msg_logging_ack.h \
		include/Output/common/mavlink_msg_video_stream_information.h \
		include/Output/common/mavlink_msg_video_stream_status.h \
		include/Output/common/mavlink_msg_camera_fov_status.h \
		include/Output/common/mavlink_msg_camera_tracking_image_status.h \
		include/Output/common/mavlink_msg_camera_tracking_geo_status.h \
		include/Output/common/mavlink_msg_camera_thermal_range.h \
		include/Output/common/mavlink_msg_gimbal_manager_information.h \
		include/Output/common/mavlink_msg_gimbal_manager_status.h \
		include/Output/common/mavlink_msg_gimbal_manager_set_attitude.h \
		include/Output/common/mavlink_msg_gimbal_device_information.h \
		include/Output/common/mavlink_msg_gimbal_device_set_attitude.h \
		include/Output/common/mavlink_msg_gimbal_device_attitude_status.h \
		include/Output/common/mavlink_msg_autopilot_state_for_gimbal_device.h \
		include/Output/common/mavlink_msg_gimbal_manager_set_pitchyaw.h \
		include/Output/common/mavlink_msg_gimbal_manager_set_manual_control.h \
		include/Output/common/mavlink_msg_esc_info.h \
		include/Output/common/mavlink_msg_esc_status.h \
		include/Output/common/mavlink_msg_wifi_config_ap.h \
		include/Output/common/mavlink_msg_ais_vessel.h \
		include/Output/common/mavlink_msg_uavcan_node_status.h \
		include/Output/common/mavlink_msg_uavcan_node_info.h \
		include/Output/common/mavlink_msg_param_ext_request_read.h \
		include/Output/common/mavlink_msg_param_ext_request_list.h \
		include/Output/common/mavlink_msg_param_ext_value.h \
		include/Output/common/mavlink_msg_param_ext_set.h \
		include/Output/common/mavlink_msg_param_ext_ack.h \
		include/Output/common/mavlink_msg_obstacle_distance.h \
		include/Output/common/mavlink_msg_odometry.h \
		include/Output/common/mavlink_msg_trajectory_representation_waypoints.h \
		include/Output/common/mavlink_msg_trajectory_representation_bezier.h \
		include/Output/common/mavlink_msg_cellular_status.h \
		include/Output/common/mavlink_msg_isbd_link_status.h \
		include/Output/common/mavlink_msg_cellular_config.h \
		include/Output/common/mavlink_msg_raw_rpm.h \
		include/Output/common/mavlink_msg_utm_global_position.h \
		include/Output/common/mavlink_msg_debug_float_array.h \
		include/Output/common/mavlink_msg_orbit_execution_status.h \
		include/Output/common/mavlink_msg_smart_battery_info.h \
		include/Output/common/mavlink_msg_fuel_status.h \
		include/Output/common/mavlink_msg_battery_info.h \
		include/Output/common/mavlink_msg_generator_status.h \
		include/Output/common/mavlink_msg_actuator_output_status.h \
		include/Output/common/mavlink_msg_time_estimate_to_target.h \
		include/Output/common/mavlink_msg_tunnel.h \
		include/Output/common/mavlink_msg_can_frame.h \
		include/Output/common/mavlink_msg_onboard_computer_status.h \
		include/Output/common/mavlink_msg_component_information.h \
		include/Output/common/mavlink_msg_component_information_basic.h \
		include/Output/common/mavlink_msg_component_metadata.h \
		include/Output/common/mavlink_msg_play_tune_v2.h \
		include/Output/common/mavlink_msg_supported_tunes.h \
		include/Output/common/mavlink_msg_event.h \
		include/Output/common/mavlink_msg_current_event_sequence.h \
		include/Output/common/mavlink_msg_request_event.h \
		include/Output/common/mavlink_msg_response_event_error.h \
		include/Output/common/mavlink_msg_available_modes.h \
		include/Output/common/mavlink_msg_current_mode.h \
		include/Output/common/mavlink_msg_available_modes_monitor.h \
		include/Output/common/mavlink_msg_illuminator_status.h \
		include/Output/common/mavlink_msg_canfd_frame.h \
		include/Output/common/mavlink_msg_can_filter_modify.h \
		include/Output/common/mavlink_msg_wheel_distance.h \
		include/Output/common/mavlink_msg_winch_status.h \
		include/Output/common/mavlink_msg_open_drone_id_basic_id.h \
		include/Output/common/mavlink_msg_open_drone_id_location.h \
		include/Output/common/mavlink_msg_open_drone_id_authentication.h \
		include/Output/common/mavlink_msg_open_drone_id_self_id.h \
		include/Output/common/mavlink_msg_open_drone_id_system.h \
		include/Output/common/mavlink_msg_open_drone_id_operator_id.h \
		include/Output/common/mavlink_msg_open_drone_id_message_pack.h \
		include/Output/common/mavlink_msg_open_drone_id_arm_status.h \
		include/Output/common/mavlink_msg_open_drone_id_system_update.h \
		include/Output/common/mavlink_msg_hygrometer_sensor.h \
		include/Output/standard/standard.h \
		include/Output/minimal/minimal.h \
		include/Output/minimal/mavlink_msg_heartbeat.h \
		include/Output/minimal/mavlink_msg_protocol_version.h \
		include/Output/mavlink_get_info.h \
		include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

application.o: src/application.cpp include/application.h \
		include/camera_handler.h \
		include/frame_buffer_manager.h \
		include/control_unit.h \
		include/tracker_interface.h \
		include/video_handler.h \
		include/model_manager.h \
		include/model.h \
		include/tracker_manager.h \
		include/visualizer.h \
		include/navigation_unit.h \
		include/failure_handler.h \
		include/mavlink.h \
		include/Output/common/mavlink.h \
		include/Output/common/version.h \
		include/Output/common/common.h \
		include/Output/protocol.h \
		include/Output/mavlink_types.h \
		include/Output/mavlink_helpers.h \
		include/Output/checksum.h \
		include/Output/mavlink_conversions.h \
		include/Output/mavlink_sha256.h \
		include/Output/common/mavlink_msg_sys_status.h \
		include/Output/common/mavlink_msg_system_time.h \
		include/Output/common/mavlink_msg_ping.h \
		include/Output/common/mavlink_msg_change_operator_control.h \
		include/Output/common/mavlink_msg_change_operator_control_ack.h \
		include/Output/common/mavlink_msg_auth_key.h \
		include/Output/common/mavlink_msg_link_node_status.h \
		include/Output/common/mavlink_msg_set_mode.h \
		include/Output/common/mavlink_msg_param_request_read.h \
		include/Output/common/mavlink_msg_param_request_list.h \
		include/Output/common/mavlink_msg_param_value.h \
		include/Output/common/mavlink_msg_param_set.h \
		include/Output/common/mavlink_msg_gps_raw_int.h \
		include/Output/common/mavlink_msg_gps_status.h \
		include/Output/common/mavlink_msg_scaled_imu.h \
		include/Output/common/mavlink_msg_raw_imu.h \
		include/Output/common/mavlink_msg_raw_pressure.h \
		include/Output/common/mavlink_msg_scaled_pressure.h \
		include/Output/common/mavlink_msg_attitude.h \
		include/Output/common/mavlink_msg_attitude_quaternion.h \
		include/Output/common/mavlink_msg_local_position_ned.h \
		include/Output/common/mavlink_msg_global_position_int.h \
		include/Output/common/mavlink_msg_rc_channels_scaled.h \
		include/Output/common/mavlink_msg_rc_channels_raw.h \
		include/Output/common/mavlink_msg_servo_output_raw.h \
		include/Output/common/mavlink_msg_mission_request_partial_list.h \
		include/Output/common/mavlink_msg_mission_write_partial_list.h \
		include/Output/common/mavlink_msg_mission_item.h \
		include/Output/common/mavlink_msg_mission_request.h \
		include/Output/common/mavlink_msg_mission_set_current.h \
		include/Output/common/mavlink_msg_mission_current.h \
		include/Output/common/mavlink_msg_mission_request_list.h \
		include/Output/common/mavlink_msg_mission_count.h \
		include/Output/common/mavlink_msg_mission_clear_all.h \
		include/Output/common/mavlink_msg_mission_item_reached.h \
		include/Output/common/mavlink_msg_mission_ack.h \
		include/Output/common/mavlink_msg_set_gps_global_origin.h \
		include/Output/common/mavlink_msg_gps_global_origin.h \
		include/Output/common/mavlink_msg_param_map_rc.h \
		include/Output/common/mavlink_msg_mission_request_int.h \
		include/Output/common/mavlink_msg_safety_set_allowed_area.h \
		include/Output/common/mavlink_msg_safety_allowed_area.h \
		include/Output/common/mavlink_msg_attitude_quaternion_cov.h \
		include/Output/common/mavlink_msg_nav_controller_output.h \
		include/Output/common/mavlink_msg_global_position_int_cov.h \
		include/Output/common/mavlink_msg_local_position_ned_cov.h \
		include/Output/common/mavlink_msg_rc_channels.h \
		include/Output/common/mavlink_msg_request_data_stream.h \
		include/Output/common/mavlink_msg_data_stream.h \
		include/Output/common/mavlink_msg_manual_control.h \
		include/Output/common/mavlink_msg_rc_channels_override.h \
		include/Output/common/mavlink_msg_mission_item_int.h \
		include/Output/common/mavlink_msg_vfr_hud.h \
		include/Output/common/mavlink_msg_command_int.h \
		include/Output/common/mavlink_msg_command_long.h \
		include/Output/common/mavlink_msg_command_ack.h \
		include/Output/common/mavlink_msg_command_cancel.h \
		include/Output/common/mavlink_msg_manual_setpoint.h \
		include/Output/common/mavlink_msg_set_attitude_target.h \
		include/Output/common/mavlink_msg_attitude_target.h \
		include/Output/common/mavlink_msg_set_position_target_local_ned.h \
		include/Output/common/mavlink_msg_position_target_local_ned.h \
		include/Output/common/mavlink_msg_set_position_target_global_int.h \
		include/Output/common/mavlink_msg_position_target_global_int.h \
		include/Output/common/mavlink_msg_local_position_ned_system_global_offset.h \
		include/Output/common/mavlink_msg_hil_state.h \
		include/Output/common/mavlink_msg_hil_controls.h \
		include/Output/common/mavlink_msg_hil_rc_inputs_raw.h \
		include/Output/common/mavlink_msg_hil_actuator_controls.h \
		include/Output/common/mavlink_msg_optical_flow.h \
		include/Output/common/mavlink_msg_global_vision_position_estimate.h \
		include/Output/common/mavlink_msg_vision_position_estimate.h \
		include/Output/common/mavlink_msg_vision_speed_estimate.h \
		include/Output/common/mavlink_msg_vicon_position_estimate.h \
		include/Output/common/mavlink_msg_highres_imu.h \
		include/Output/common/mavlink_msg_optical_flow_rad.h \
		include/Output/common/mavlink_msg_hil_sensor.h \
		include/Output/common/mavlink_msg_sim_state.h \
		include/Output/common/mavlink_msg_radio_status.h \
		include/Output/common/mavlink_msg_file_transfer_protocol.h \
		include/Output/common/mavlink_msg_timesync.h \
		include/Output/common/mavlink_msg_camera_trigger.h \
		include/Output/common/mavlink_msg_hil_gps.h \
		include/Output/common/mavlink_msg_hil_optical_flow.h \
		include/Output/common/mavlink_msg_hil_state_quaternion.h \
		include/Output/common/mavlink_msg_scaled_imu2.h \
		include/Output/common/mavlink_msg_log_request_list.h \
		include/Output/common/mavlink_msg_log_entry.h \
		include/Output/common/mavlink_msg_log_request_data.h \
		include/Output/common/mavlink_msg_log_data.h \
		include/Output/common/mavlink_msg_log_erase.h \
		include/Output/common/mavlink_msg_log_request_end.h \
		include/Output/common/mavlink_msg_gps_inject_data.h \
		include/Output/common/mavlink_msg_gps2_raw.h \
		include/Output/common/mavlink_msg_power_status.h \
		include/Output/common/mavlink_msg_serial_control.h \
		include/Output/common/mavlink_msg_gps_rtk.h \
		include/Output/common/mavlink_msg_gps2_rtk.h \
		include/Output/common/mavlink_msg_scaled_imu3.h \
		include/Output/common/mavlink_msg_data_transmission_handshake.h \
		include/Output/common/mavlink_msg_encapsulated_data.h \
		include/Output/common/mavlink_msg_distance_sensor.h \
		include/Output/common/mavlink_msg_terrain_request.h \
		include/Output/common/mavlink_msg_terrain_data.h \
		include/Output/common/mavlink_msg_terrain_check.h \
		include/Output/common/mavlink_msg_terrain_report.h \
		include/Output/common/mavlink_msg_scaled_pressure2.h \
		include/Output/common/mavlink_msg_att_pos_mocap.h \
		include/Output/common/mavlink_msg_set_actuator_control_target.h \
		include/Output/common/mavlink_msg_actuator_control_target.h \
		include/Output/common/mavlink_msg_altitude.h \
		include/Output/common/mavlink_msg_resource_request.h \
		include/Output/common/mavlink_msg_scaled_pressure3.h \
		include/Output/common/mavlink_msg_follow_target.h \
		include/Output/common/mavlink_msg_control_system_state.h \
		include/Output/common/mavlink_msg_battery_status.h \
		include/Output/common/mavlink_msg_autopilot_version.h \
		include/Output/common/mavlink_msg_landing_target.h \
		include/Output/common/mavlink_msg_fence_status.h \
		include/Output/common/mavlink_msg_mag_cal_report.h \
		include/Output/common/mavlink_msg_efi_status.h \
		include/Output/common/mavlink_msg_estimator_status.h \
		include/Output/common/mavlink_msg_wind_cov.h \
		include/Output/common/mavlink_msg_gps_input.h \
		include/Output/common/mavlink_msg_gps_rtcm_data.h \
		include/Output/common/mavlink_msg_high_latency.h \
		include/Output/common/mavlink_msg_high_latency2.h \
		include/Output/common/mavlink_msg_vibration.h \
		include/Output/common/mavlink_msg_home_position.h \
		include/Output/common/mavlink_msg_set_home_position.h \
		include/Output/common/mavlink_msg_message_interval.h \
		include/Output/common/mavlink_msg_extended_sys_state.h \
		include/Output/common/mavlink_msg_adsb_vehicle.h \
		include/Output/common/mavlink_msg_collision.h \
		include/Output/common/mavlink_msg_v2_extension.h \
		include/Output/common/mavlink_msg_memory_vect.h \
		include/Output/common/mavlink_msg_debug_vect.h \
		include/Output/common/mavlink_msg_named_value_float.h \
		include/Output/common/mavlink_msg_named_value_int.h \
		include/Output/common/mavlink_msg_statustext.h \
		include/Output/common/mavlink_msg_debug.h \
		include/Output/common/mavlink_msg_setup_signing.h \
		include/Output/common/mavlink_msg_button_change.h \
		include/Output/common/mavlink_msg_play_tune.h \
		include/Output/common/mavlink_msg_camera_information.h \
		include/Output/common/mavlink_msg_camera_settings.h \
		include/Output/common/mavlink_msg_storage_information.h \
		include/Output/common/mavlink_msg_camera_capture_status.h \
		include/Output/common/mavlink_msg_camera_image_captured.h \
		include/Output/common/mavlink_msg_flight_information.h \
		include/Output/common/mavlink_msg_mount_orientation.h \
		include/Output/common/mavlink_msg_logging_data.h \
		include/Output/common/mavlink_msg_logging_data_acked.h \
		include/Output/common/mavlink_msg_logging_ack.h \
		include/Output/common/mavlink_msg_video_stream_information.h \
		include/Output/common/mavlink_msg_video_stream_status.h \
		include/Output/common/mavlink_msg_camera_fov_status.h \
		include/Output/common/mavlink_msg_camera_tracking_image_status.h \
		include/Output/common/mavlink_msg_camera_tracking_geo_status.h \
		include/Output/common/mavlink_msg_camera_thermal_range.h \
		include/Output/common/mavlink_msg_gimbal_manager_information.h \
		include/Output/common/mavlink_msg_gimbal_manager_status.h \
		include/Output/common/mavlink_msg_gimbal_manager_set_attitude.h \
		include/Output/common/mavlink_msg_gimbal_device_information.h \
		include/Output/common/mavlink_msg_gimbal_device_set_attitude.h \
		include/Output/common/mavlink_msg_gimbal_device_attitude_status.h \
		include/Output/common/mavlink_msg_autopilot_state_for_gimbal_device.h \
		include/Output/common/mavlink_msg_gimbal_manager_set_pitchyaw.h \
		include/Output/common/mavlink_msg_gimbal_manager_set_manual_control.h \
		include/Output/common/mavlink_msg_esc_info.h \
		include/Output/common/mavlink_msg_esc_status.h \
		include/Output/common/mavlink_msg_wifi_config_ap.h \
		include/Output/common/mavlink_msg_ais_vessel.h \
		include/Output/common/mavlink_msg_uavcan_node_status.h \
		include/Output/common/mavlink_msg_uavcan_node_info.h \
		include/Output/common/mavlink_msg_param_ext_request_read.h \
		include/Output/common/mavlink_msg_param_ext_request_list.h \
		include/Output/common/mavlink_msg_param_ext_value.h \
		include/Output/common/mavlink_msg_param_ext_set.h \
		include/Output/common/mavlink_msg_param_ext_ack.h \
		include/Output/common/mavlink_msg_obstacle_distance.h \
		include/Output/common/mavlink_msg_odometry.h \
		include/Output/common/mavlink_msg_trajectory_representation_waypoints.h \
		include/Output/common/mavlink_msg_trajectory_representation_bezier.h \
		include/Output/common/mavlink_msg_cellular_status.h \
		include/Output/common/mavlink_msg_isbd_link_status.h \
		include/Output/common/mavlink_msg_cellular_config.h \
		include/Output/common/mavlink_msg_raw_rpm.h \
		include/Output/common/mavlink_msg_utm_global_position.h \
		include/Output/common/mavlink_msg_debug_float_array.h \
		include/Output/common/mavlink_msg_orbit_execution_status.h \
		include/Output/common/mavlink_msg_smart_battery_info.h \
		include/Output/common/mavlink_msg_fuel_status.h \
		include/Output/common/mavlink_msg_battery_info.h \
		include/Output/common/mavlink_msg_generator_status.h \
		include/Output/common/mavlink_msg_actuator_output_status.h \
		include/Output/common/mavlink_msg_time_estimate_to_target.h \
		include/Output/common/mavlink_msg_tunnel.h \
		include/Output/common/mavlink_msg_can_frame.h \
		include/Output/common/mavlink_msg_onboard_computer_status.h \
		include/Output/common/mavlink_msg_component_information.h \
		include/Output/common/mavlink_msg_component_information_basic.h \
		include/Output/common/mavlink_msg_component_metadata.h \
		include/Output/common/mavlink_msg_play_tune_v2.h \
		include/Output/common/mavlink_msg_supported_tunes.h \
		include/Output/common/mavlink_msg_event.h \
		include/Output/common/mavlink_msg_current_event_sequence.h \
		include/Output/common/mavlink_msg_request_event.h \
		include/Output/common/mavlink_msg_response_event_error.h \
		include/Output/common/mavlink_msg_available_modes.h \
		include/Output/common/mavlink_msg_current_mode.h \
		include/Output/common/mavlink_msg_available_modes_monitor.h \
		include/Output/common/mavlink_msg_illuminator_status.h \
		include/Output/common/mavlink_msg_canfd_frame.h \
		include/Output/common/mavlink_msg_can_filter_modify.h \
		include/Output/common/mavlink_msg_wheel_distance.h \
		include/Output/common/mavlink_msg_winch_status.h \
		include/Output/common/mavlink_msg_open_drone_id_basic_id.h \
		include/Output/common/mavlink_msg_open_drone_id_location.h \
		include/Output/common/mavlink_msg_open_drone_id_authentication.h \
		include/Output/common/mavlink_msg_open_drone_id_self_id.h \
		include/Output/common/mavlink_msg_open_drone_id_system.h \
		include/Output/common/mavlink_msg_open_drone_id_operator_id.h \
		include/Output/common/mavlink_msg_open_drone_id_message_pack.h \
		include/Output/common/mavlink_msg_open_drone_id_arm_status.h \
		include/Output/common/mavlink_msg_open_drone_id_system_update.h \
		include/Output/common/mavlink_msg_hygrometer_sensor.h \
		include/Output/standard/standard.h \
		include/Output/minimal/minimal.h \
		include/Output/minimal/mavlink_msg_heartbeat.h \
		include/Output/minimal/mavlink_msg_protocol_version.h \
		include/Output/mavlink_get_info.h \
		include/config_utils.h \
		include/resource_monitor.h \
		include/detection_manager.h \
		include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o application.o src/application.cpp

mainwindow.o: src/mainwindow.cpp include/mainwindow.h \
		include/application.h \
		include/camera_handler.h \
		include/frame_buffer_manager.h \
		include/control_unit.h \
		include/tracker_interface.h \
		include/video_handler.h \
		include/model_manager.h \
		include/model.h \
		include/tracker_manager.h \
		include/visualizer.h \
		include/navigation_unit.h \
		include/failure_handler.h \
		include/mavlink.h \
		include/Output/common/mavlink.h \
		include/Output/common/version.h \
		include/Output/common/common.h \
		include/Output/protocol.h \
		include/Output/mavlink_types.h \
		include/Output/mavlink_helpers.h \
		include/Output/checksum.h \
		include/Output/mavlink_conversions.h \
		include/Output/mavlink_sha256.h \
		include/Output/common/mavlink_msg_sys_status.h \
		include/Output/common/mavlink_msg_system_time.h \
		include/Output/common/mavlink_msg_ping.h \
		include/Output/common/mavlink_msg_change_operator_control.h \
		include/Output/common/mavlink_msg_change_operator_control_ack.h \
		include/Output/common/mavlink_msg_auth_key.h \
		include/Output/common/mavlink_msg_link_node_status.h \
		include/Output/common/mavlink_msg_set_mode.h \
		include/Output/common/mavlink_msg_param_request_read.h \
		include/Output/common/mavlink_msg_param_request_list.h \
		include/Output/common/mavlink_msg_param_value.h \
		include/Output/common/mavlink_msg_param_set.h \
		include/Output/common/mavlink_msg_gps_raw_int.h \
		include/Output/common/mavlink_msg_gps_status.h \
		include/Output/common/mavlink_msg_scaled_imu.h \
		include/Output/common/mavlink_msg_raw_imu.h \
		include/Output/common/mavlink_msg_raw_pressure.h \
		include/Output/common/mavlink_msg_scaled_pressure.h \
		include/Output/common/mavlink_msg_attitude.h \
		include/Output/common/mavlink_msg_attitude_quaternion.h \
		include/Output/common/mavlink_msg_local_position_ned.h \
		include/Output/common/mavlink_msg_global_position_int.h \
		include/Output/common/mavlink_msg_rc_channels_scaled.h \
		include/Output/common/mavlink_msg_rc_channels_raw.h \
		include/Output/common/mavlink_msg_servo_output_raw.h \
		include/Output/common/mavlink_msg_mission_request_partial_list.h \
		include/Output/common/mavlink_msg_mission_write_partial_list.h \
		include/Output/common/mavlink_msg_mission_item.h \
		include/Output/common/mavlink_msg_mission_request.h \
		include/Output/common/mavlink_msg_mission_set_current.h \
		include/Output/common/mavlink_msg_mission_current.h \
		include/Output/common/mavlink_msg_mission_request_list.h \
		include/Output/common/mavlink_msg_mission_count.h \
		include/Output/common/mavlink_msg_mission_clear_all.h \
		include/Output/common/mavlink_msg_mission_item_reached.h \
		include/Output/common/mavlink_msg_mission_ack.h \
		include/Output/common/mavlink_msg_set_gps_global_origin.h \
		include/Output/common/mavlink_msg_gps_global_origin.h \
		include/Output/common/mavlink_msg_param_map_rc.h \
		include/Output/common/mavlink_msg_mission_request_int.h \
		include/Output/common/mavlink_msg_safety_set_allowed_area.h \
		include/Output/common/mavlink_msg_safety_allowed_area.h \
		include/Output/common/mavlink_msg_attitude_quaternion_cov.h \
		include/Output/common/mavlink_msg_nav_controller_output.h \
		include/Output/common/mavlink_msg_global_position_int_cov.h \
		include/Output/common/mavlink_msg_local_position_ned_cov.h \
		include/Output/common/mavlink_msg_rc_channels.h \
		include/Output/common/mavlink_msg_request_data_stream.h \
		include/Output/common/mavlink_msg_data_stream.h \
		include/Output/common/mavlink_msg_manual_control.h \
		include/Output/common/mavlink_msg_rc_channels_override.h \
		include/Output/common/mavlink_msg_mission_item_int.h \
		include/Output/common/mavlink_msg_vfr_hud.h \
		include/Output/common/mavlink_msg_command_int.h \
		include/Output/common/mavlink_msg_command_long.h \
		include/Output/common/mavlink_msg_command_ack.h \
		include/Output/common/mavlink_msg_command_cancel.h \
		include/Output/common/mavlink_msg_manual_setpoint.h \
		include/Output/common/mavlink_msg_set_attitude_target.h \
		include/Output/common/mavlink_msg_attitude_target.h \
		include/Output/common/mavlink_msg_set_position_target_local_ned.h \
		include/Output/common/mavlink_msg_position_target_local_ned.h \
		include/Output/common/mavlink_msg_set_position_target_global_int.h \
		include/Output/common/mavlink_msg_position_target_global_int.h \
		include/Output/common/mavlink_msg_local_position_ned_system_global_offset.h \
		include/Output/common/mavlink_msg_hil_state.h \
		include/Output/common/mavlink_msg_hil_controls.h \
		include/Output/common/mavlink_msg_hil_rc_inputs_raw.h \
		include/Output/common/mavlink_msg_hil_actuator_controls.h \
		include/Output/common/mavlink_msg_optical_flow.h \
		include/Output/common/mavlink_msg_global_vision_position_estimate.h \
		include/Output/common/mavlink_msg_vision_position_estimate.h \
		include/Output/common/mavlink_msg_vision_speed_estimate.h \
		include/Output/common/mavlink_msg_vicon_position_estimate.h \
		include/Output/common/mavlink_msg_highres_imu.h \
		include/Output/common/mavlink_msg_optical_flow_rad.h \
		include/Output/common/mavlink_msg_hil_sensor.h \
		include/Output/common/mavlink_msg_sim_state.h \
		include/Output/common/mavlink_msg_radio_status.h \
		include/Output/common/mavlink_msg_file_transfer_protocol.h \
		include/Output/common/mavlink_msg_timesync.h \
		include/Output/common/mavlink_msg_camera_trigger.h \
		include/Output/common/mavlink_msg_hil_gps.h \
		include/Output/common/mavlink_msg_hil_optical_flow.h \
		include/Output/common/mavlink_msg_hil_state_quaternion.h \
		include/Output/common/mavlink_msg_scaled_imu2.h \
		include/Output/common/mavlink_msg_log_request_list.h \
		include/Output/common/mavlink_msg_log_entry.h \
		include/Output/common/mavlink_msg_log_request_data.h \
		include/Output/common/mavlink_msg_log_data.h \
		include/Output/common/mavlink_msg_log_erase.h \
		include/Output/common/mavlink_msg_log_request_end.h \
		include/Output/common/mavlink_msg_gps_inject_data.h \
		include/Output/common/mavlink_msg_gps2_raw.h \
		include/Output/common/mavlink_msg_power_status.h \
		include/Output/common/mavlink_msg_serial_control.h \
		include/Output/common/mavlink_msg_gps_rtk.h \
		include/Output/common/mavlink_msg_gps2_rtk.h \
		include/Output/common/mavlink_msg_scaled_imu3.h \
		include/Output/common/mavlink_msg_data_transmission_handshake.h \
		include/Output/common/mavlink_msg_encapsulated_data.h \
		include/Output/common/mavlink_msg_distance_sensor.h \
		include/Output/common/mavlink_msg_terrain_request.h \
		include/Output/common/mavlink_msg_terrain_data.h \
		include/Output/common/mavlink_msg_terrain_check.h \
		include/Output/common/mavlink_msg_terrain_report.h \
		include/Output/common/mavlink_msg_scaled_pressure2.h \
		include/Output/common/mavlink_msg_att_pos_mocap.h \
		include/Output/common/mavlink_msg_set_actuator_control_target.h \
		include/Output/common/mavlink_msg_actuator_control_target.h \
		include/Output/common/mavlink_msg_altitude.h \
		include/Output/common/mavlink_msg_resource_request.h \
		include/Output/common/mavlink_msg_scaled_pressure3.h \
		include/Output/common/mavlink_msg_follow_target.h \
		include/Output/common/mavlink_msg_control_system_state.h \
		include/Output/common/mavlink_msg_battery_status.h \
		include/Output/common/mavlink_msg_autopilot_version.h \
		include/Output/common/mavlink_msg_landing_target.h \
		include/Output/common/mavlink_msg_fence_status.h \
		include/Output/common/mavlink_msg_mag_cal_report.h \
		include/Output/common/mavlink_msg_efi_status.h \
		include/Output/common/mavlink_msg_estimator_status.h \
		include/Output/common/mavlink_msg_wind_cov.h \
		include/Output/common/mavlink_msg_gps_input.h \
		include/Output/common/mavlink_msg_gps_rtcm_data.h \
		include/Output/common/mavlink_msg_high_latency.h \
		include/Output/common/mavlink_msg_high_latency2.h \
		include/Output/common/mavlink_msg_vibration.h \
		include/Output/common/mavlink_msg_home_position.h \
		include/Output/common/mavlink_msg_set_home_position.h \
		include/Output/common/mavlink_msg_message_interval.h \
		include/Output/common/mavlink_msg_extended_sys_state.h \
		include/Output/common/mavlink_msg_adsb_vehicle.h \
		include/Output/common/mavlink_msg_collision.h \
		include/Output/common/mavlink_msg_v2_extension.h \
		include/Output/common/mavlink_msg_memory_vect.h \
		include/Output/common/mavlink_msg_debug_vect.h \
		include/Output/common/mavlink_msg_named_value_float.h \
		include/Output/common/mavlink_msg_named_value_int.h \
		include/Output/common/mavlink_msg_statustext.h \
		include/Output/common/mavlink_msg_debug.h \
		include/Output/common/mavlink_msg_setup_signing.h \
		include/Output/common/mavlink_msg_button_change.h \
		include/Output/common/mavlink_msg_play_tune.h \
		include/Output/common/mavlink_msg_camera_information.h \
		include/Output/common/mavlink_msg_camera_settings.h \
		include/Output/common/mavlink_msg_storage_information.h \
		include/Output/common/mavlink_msg_camera_capture_status.h \
		include/Output/common/mavlink_msg_camera_image_captured.h \
		include/Output/common/mavlink_msg_flight_information.h \
		include/Output/common/mavlink_msg_mount_orientation.h \
		include/Output/common/mavlink_msg_logging_data.h \
		include/Output/common/mavlink_msg_logging_data_acked.h \
		include/Output/common/mavlink_msg_logging_ack.h \
		include/Output/common/mavlink_msg_video_stream_information.h \
		include/Output/common/mavlink_msg_video_stream_status.h \
		include/Output/common/mavlink_msg_camera_fov_status.h \
		include/Output/common/mavlink_msg_camera_tracking_image_status.h \
		include/Output/common/mavlink_msg_camera_tracking_geo_status.h \
		include/Output/common/mavlink_msg_camera_thermal_range.h \
		include/Output/common/mavlink_msg_gimbal_manager_information.h \
		include/Output/common/mavlink_msg_gimbal_manager_status.h \
		include/Output/common/mavlink_msg_gimbal_manager_set_attitude.h \
		include/Output/common/mavlink_msg_gimbal_device_information.h \
		include/Output/common/mavlink_msg_gimbal_device_set_attitude.h \
		include/Output/common/mavlink_msg_gimbal_device_attitude_status.h \
		include/Output/common/mavlink_msg_autopilot_state_for_gimbal_device.h \
		include/Output/common/mavlink_msg_gimbal_manager_set_pitchyaw.h \
		include/Output/common/mavlink_msg_gimbal_manager_set_manual_control.h \
		include/Output/common/mavlink_msg_esc_info.h \
		include/Output/common/mavlink_msg_esc_status.h \
		include/Output/common/mavlink_msg_wifi_config_ap.h \
		include/Output/common/mavlink_msg_ais_vessel.h \
		include/Output/common/mavlink_msg_uavcan_node_status.h \
		include/Output/common/mavlink_msg_uavcan_node_info.h \
		include/Output/common/mavlink_msg_param_ext_request_read.h \
		include/Output/common/mavlink_msg_param_ext_request_list.h \
		include/Output/common/mavlink_msg_param_ext_value.h \
		include/Output/common/mavlink_msg_param_ext_set.h \
		include/Output/common/mavlink_msg_param_ext_ack.h \
		include/Output/common/mavlink_msg_obstacle_distance.h \
		include/Output/common/mavlink_msg_odometry.h \
		include/Output/common/mavlink_msg_trajectory_representation_waypoints.h \
		include/Output/common/mavlink_msg_trajectory_representation_bezier.h \
		include/Output/common/mavlink_msg_cellular_status.h \
		include/Output/common/mavlink_msg_isbd_link_status.h \
		include/Output/common/mavlink_msg_cellular_config.h \
		include/Output/common/mavlink_msg_raw_rpm.h \
		include/Output/common/mavlink_msg_utm_global_position.h \
		include/Output/common/mavlink_msg_debug_float_array.h \
		include/Output/common/mavlink_msg_orbit_execution_status.h \
		include/Output/common/mavlink_msg_smart_battery_info.h \
		include/Output/common/mavlink_msg_fuel_status.h \
		include/Output/common/mavlink_msg_battery_info.h \
		include/Output/common/mavlink_msg_generator_status.h \
		include/Output/common/mavlink_msg_actuator_output_status.h \
		include/Output/common/mavlink_msg_time_estimate_to_target.h \
		include/Output/common/mavlink_msg_tunnel.h \
		include/Output/common/mavlink_msg_can_frame.h \
		include/Output/common/mavlink_msg_onboard_computer_status.h \
		include/Output/common/mavlink_msg_component_information.h \
		include/Output/common/mavlink_msg_component_information_basic.h \
		include/Output/common/mavlink_msg_component_metadata.h \
		include/Output/common/mavlink_msg_play_tune_v2.h \
		include/Output/common/mavlink_msg_supported_tunes.h \
		include/Output/common/mavlink_msg_event.h \
		include/Output/common/mavlink_msg_current_event_sequence.h \
		include/Output/common/mavlink_msg_request_event.h \
		include/Output/common/mavlink_msg_response_event_error.h \
		include/Output/common/mavlink_msg_available_modes.h \
		include/Output/common/mavlink_msg_current_mode.h \
		include/Output/common/mavlink_msg_available_modes_monitor.h \
		include/Output/common/mavlink_msg_illuminator_status.h \
		include/Output/common/mavlink_msg_canfd_frame.h \
		include/Output/common/mavlink_msg_can_filter_modify.h \
		include/Output/common/mavlink_msg_wheel_distance.h \
		include/Output/common/mavlink_msg_winch_status.h \
		include/Output/common/mavlink_msg_open_drone_id_basic_id.h \
		include/Output/common/mavlink_msg_open_drone_id_location.h \
		include/Output/common/mavlink_msg_open_drone_id_authentication.h \
		include/Output/common/mavlink_msg_open_drone_id_self_id.h \
		include/Output/common/mavlink_msg_open_drone_id_system.h \
		include/Output/common/mavlink_msg_open_drone_id_operator_id.h \
		include/Output/common/mavlink_msg_open_drone_id_message_pack.h \
		include/Output/common/mavlink_msg_open_drone_id_arm_status.h \
		include/Output/common/mavlink_msg_open_drone_id_system_update.h \
		include/Output/common/mavlink_msg_hygrometer_sensor.h \
		include/Output/standard/standard.h \
		include/Output/minimal/minimal.h \
		include/Output/minimal/mavlink_msg_heartbeat.h \
		include/Output/minimal/mavlink_msg_protocol_version.h \
		include/Output/mavlink_get_info.h \
		include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

visualizer.o: src/visualizer.cpp include/visualizer.h \
		include/model.h \
		include/navigation_unit.h \
		include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o visualizer.o src/visualizer.cpp

failure_handler.o: src/failure_handler.cpp include/failure_handler.h \
		include/model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o failure_handler.o src/failure_handler.cpp

camera_handler.o: src/camera_handler.cpp include/camera_handler.h \
		include/frame_buffer_manager.h \
		include/control_unit.h \
		include/tracker_interface.h \
		include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera_handler.o src/camera_handler.cpp

video_handler.o: src/video_handler.cpp include/video_handler.h \
		include/frame_buffer_manager.h \
		include/control_unit.h \
		include/tracker_interface.h \
		include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o video_handler.o src/video_handler.cpp

config_utils.o: src/config_utils.cpp include/config_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config_utils.o src/config_utils.cpp

control_unit.o: src/control_unit.cpp include/control_unit.h \
		include/tracker_interface.h \
		include/frame_buffer_manager.h \
		include/model_manager.h \
		include/model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o control_unit.o src/control_unit.cpp

frame_buffer_manager.o: src/frame_buffer_manager.cpp include/frame_buffer_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frame_buffer_manager.o src/frame_buffer_manager.cpp

model.o: src/model.cpp include/model.h \
		include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o src/model.cpp

model_manager.o: src/model_manager.cpp include/model_manager.h \
		include/model.h \
		include/detection/color_detector.h \
		include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model_manager.o src/model_manager.cpp

resource_monitor.o: src/resource_monitor.cpp include/resource_monitor.h \
		include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resource_monitor.o src/resource_monitor.cpp

siamfc_pp_tracker.o: src/tracking/siamfc_pp_tracker.cpp include/tracking/siamfc_pp_tracker.h \
		include/tracker_interface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o siamfc_pp_tracker.o src/tracking/siamfc_pp_tracker.cpp

vittracker.o: src/tracking/vittracker.cpp include/tracking/vittracker.h \
		include/tracker_interface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vittracker.o src/tracking/vittracker.cpp

csrt_tracker.o: src/tracking/csrt_tracker.cpp include/tracking/csrt_tracker.h \
		include/tracker_interface.h \
		include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o csrt_tracker.o src/tracking/csrt_tracker.cpp

tracker_manager.o: src/tracker_manager.cpp include/tracker_manager.h \
		include/tracker_interface.h \
		include/tracking/vittracker.h \
		include/tracking/siamfc_pp_tracker.h \
		include/tracking/csrt_tracker.h \
		include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tracker_manager.o src/tracker_manager.cpp

detection_manager.o: src/detection_manager.cpp include/detection_manager.h \
		include/model_manager.h \
		include/model.h \
		include/control_unit.h \
		include/tracker_interface.h \
		include/failure_handler.h \
		include/visualizer.h \
		include/navigation_unit.h \
		include/frame_buffer_manager.h \
		include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detection_manager.o src/detection_manager.cpp

yolo_detector.o: src/detection/yolo_detector.cpp include/detection/yolo_detector.h \
		include/model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o yolo_detector.o src/detection/yolo_detector.cpp

color_detector.o: src/detection/color_detector.cpp include/detection/color_detector.h \
		include/model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o color_detector.o src/detection/color_detector.cpp

mavlink.o: src/mavlink.cpp include/mavlink.h \
		include/Output/common/mavlink.h \
		include/Output/common/version.h \
		include/Output/common/common.h \
		include/Output/protocol.h \
		include/Output/mavlink_types.h \
		include/Output/mavlink_helpers.h \
		include/Output/checksum.h \
		include/Output/mavlink_conversions.h \
		include/Output/mavlink_sha256.h \
		include/Output/common/mavlink_msg_sys_status.h \
		include/Output/common/mavlink_msg_system_time.h \
		include/Output/common/mavlink_msg_ping.h \
		include/Output/common/mavlink_msg_change_operator_control.h \
		include/Output/common/mavlink_msg_change_operator_control_ack.h \
		include/Output/common/mavlink_msg_auth_key.h \
		include/Output/common/mavlink_msg_link_node_status.h \
		include/Output/common/mavlink_msg_set_mode.h \
		include/Output/common/mavlink_msg_param_request_read.h \
		include/Output/common/mavlink_msg_param_request_list.h \
		include/Output/common/mavlink_msg_param_value.h \
		include/Output/common/mavlink_msg_param_set.h \
		include/Output/common/mavlink_msg_gps_raw_int.h \
		include/Output/common/mavlink_msg_gps_status.h \
		include/Output/common/mavlink_msg_scaled_imu.h \
		include/Output/common/mavlink_msg_raw_imu.h \
		include/Output/common/mavlink_msg_raw_pressure.h \
		include/Output/common/mavlink_msg_scaled_pressure.h \
		include/Output/common/mavlink_msg_attitude.h \
		include/Output/common/mavlink_msg_attitude_quaternion.h \
		include/Output/common/mavlink_msg_local_position_ned.h \
		include/Output/common/mavlink_msg_global_position_int.h \
		include/Output/common/mavlink_msg_rc_channels_scaled.h \
		include/Output/common/mavlink_msg_rc_channels_raw.h \
		include/Output/common/mavlink_msg_servo_output_raw.h \
		include/Output/common/mavlink_msg_mission_request_partial_list.h \
		include/Output/common/mavlink_msg_mission_write_partial_list.h \
		include/Output/common/mavlink_msg_mission_item.h \
		include/Output/common/mavlink_msg_mission_request.h \
		include/Output/common/mavlink_msg_mission_set_current.h \
		include/Output/common/mavlink_msg_mission_current.h \
		include/Output/common/mavlink_msg_mission_request_list.h \
		include/Output/common/mavlink_msg_mission_count.h \
		include/Output/common/mavlink_msg_mission_clear_all.h \
		include/Output/common/mavlink_msg_mission_item_reached.h \
		include/Output/common/mavlink_msg_mission_ack.h \
		include/Output/common/mavlink_msg_set_gps_global_origin.h \
		include/Output/common/mavlink_msg_gps_global_origin.h \
		include/Output/common/mavlink_msg_param_map_rc.h \
		include/Output/common/mavlink_msg_mission_request_int.h \
		include/Output/common/mavlink_msg_safety_set_allowed_area.h \
		include/Output/common/mavlink_msg_safety_allowed_area.h \
		include/Output/common/mavlink_msg_attitude_quaternion_cov.h \
		include/Output/common/mavlink_msg_nav_controller_output.h \
		include/Output/common/mavlink_msg_global_position_int_cov.h \
		include/Output/common/mavlink_msg_local_position_ned_cov.h \
		include/Output/common/mavlink_msg_rc_channels.h \
		include/Output/common/mavlink_msg_request_data_stream.h \
		include/Output/common/mavlink_msg_data_stream.h \
		include/Output/common/mavlink_msg_manual_control.h \
		include/Output/common/mavlink_msg_rc_channels_override.h \
		include/Output/common/mavlink_msg_mission_item_int.h \
		include/Output/common/mavlink_msg_vfr_hud.h \
		include/Output/common/mavlink_msg_command_int.h \
		include/Output/common/mavlink_msg_command_long.h \
		include/Output/common/mavlink_msg_command_ack.h \
		include/Output/common/mavlink_msg_command_cancel.h \
		include/Output/common/mavlink_msg_manual_setpoint.h \
		include/Output/common/mavlink_msg_set_attitude_target.h \
		include/Output/common/mavlink_msg_attitude_target.h \
		include/Output/common/mavlink_msg_set_position_target_local_ned.h \
		include/Output/common/mavlink_msg_position_target_local_ned.h \
		include/Output/common/mavlink_msg_set_position_target_global_int.h \
		include/Output/common/mavlink_msg_position_target_global_int.h \
		include/Output/common/mavlink_msg_local_position_ned_system_global_offset.h \
		include/Output/common/mavlink_msg_hil_state.h \
		include/Output/common/mavlink_msg_hil_controls.h \
		include/Output/common/mavlink_msg_hil_rc_inputs_raw.h \
		include/Output/common/mavlink_msg_hil_actuator_controls.h \
		include/Output/common/mavlink_msg_optical_flow.h \
		include/Output/common/mavlink_msg_global_vision_position_estimate.h \
		include/Output/common/mavlink_msg_vision_position_estimate.h \
		include/Output/common/mavlink_msg_vision_speed_estimate.h \
		include/Output/common/mavlink_msg_vicon_position_estimate.h \
		include/Output/common/mavlink_msg_highres_imu.h \
		include/Output/common/mavlink_msg_optical_flow_rad.h \
		include/Output/common/mavlink_msg_hil_sensor.h \
		include/Output/common/mavlink_msg_sim_state.h \
		include/Output/common/mavlink_msg_radio_status.h \
		include/Output/common/mavlink_msg_file_transfer_protocol.h \
		include/Output/common/mavlink_msg_timesync.h \
		include/Output/common/mavlink_msg_camera_trigger.h \
		include/Output/common/mavlink_msg_hil_gps.h \
		include/Output/common/mavlink_msg_hil_optical_flow.h \
		include/Output/common/mavlink_msg_hil_state_quaternion.h \
		include/Output/common/mavlink_msg_scaled_imu2.h \
		include/Output/common/mavlink_msg_log_request_list.h \
		include/Output/common/mavlink_msg_log_entry.h \
		include/Output/common/mavlink_msg_log_request_data.h \
		include/Output/common/mavlink_msg_log_data.h \
		include/Output/common/mavlink_msg_log_erase.h \
		include/Output/common/mavlink_msg_log_request_end.h \
		include/Output/common/mavlink_msg_gps_inject_data.h \
		include/Output/common/mavlink_msg_gps2_raw.h \
		include/Output/common/mavlink_msg_power_status.h \
		include/Output/common/mavlink_msg_serial_control.h \
		include/Output/common/mavlink_msg_gps_rtk.h \
		include/Output/common/mavlink_msg_gps2_rtk.h \
		include/Output/common/mavlink_msg_scaled_imu3.h \
		include/Output/common/mavlink_msg_data_transmission_handshake.h \
		include/Output/common/mavlink_msg_encapsulated_data.h \
		include/Output/common/mavlink_msg_distance_sensor.h \
		include/Output/common/mavlink_msg_terrain_request.h \
		include/Output/common/mavlink_msg_terrain_data.h \
		include/Output/common/mavlink_msg_terrain_check.h \
		include/Output/common/mavlink_msg_terrain_report.h \
		include/Output/common/mavlink_msg_scaled_pressure2.h \
		include/Output/common/mavlink_msg_att_pos_mocap.h \
		include/Output/common/mavlink_msg_set_actuator_control_target.h \
		include/Output/common/mavlink_msg_actuator_control_target.h \
		include/Output/common/mavlink_msg_altitude.h \
		include/Output/common/mavlink_msg_resource_request.h \
		include/Output/common/mavlink_msg_scaled_pressure3.h \
		include/Output/common/mavlink_msg_follow_target.h \
		include/Output/common/mavlink_msg_control_system_state.h \
		include/Output/common/mavlink_msg_battery_status.h \
		include/Output/common/mavlink_msg_autopilot_version.h \
		include/Output/common/mavlink_msg_landing_target.h \
		include/Output/common/mavlink_msg_fence_status.h \
		include/Output/common/mavlink_msg_mag_cal_report.h \
		include/Output/common/mavlink_msg_efi_status.h \
		include/Output/common/mavlink_msg_estimator_status.h \
		include/Output/common/mavlink_msg_wind_cov.h \
		include/Output/common/mavlink_msg_gps_input.h \
		include/Output/common/mavlink_msg_gps_rtcm_data.h \
		include/Output/common/mavlink_msg_high_latency.h \
		include/Output/common/mavlink_msg_high_latency2.h \
		include/Output/common/mavlink_msg_vibration.h \
		include/Output/common/mavlink_msg_home_position.h \
		include/Output/common/mavlink_msg_set_home_position.h \
		include/Output/common/mavlink_msg_message_interval.h \
		include/Output/common/mavlink_msg_extended_sys_state.h \
		include/Output/common/mavlink_msg_adsb_vehicle.h \
		include/Output/common/mavlink_msg_collision.h \
		include/Output/common/mavlink_msg_v2_extension.h \
		include/Output/common/mavlink_msg_memory_vect.h \
		include/Output/common/mavlink_msg_debug_vect.h \
		include/Output/common/mavlink_msg_named_value_float.h \
		include/Output/common/mavlink_msg_named_value_int.h \
		include/Output/common/mavlink_msg_statustext.h \
		include/Output/common/mavlink_msg_debug.h \
		include/Output/common/mavlink_msg_setup_signing.h \
		include/Output/common/mavlink_msg_button_change.h \
		include/Output/common/mavlink_msg_play_tune.h \
		include/Output/common/mavlink_msg_camera_information.h \
		include/Output/common/mavlink_msg_camera_settings.h \
		include/Output/common/mavlink_msg_storage_information.h \
		include/Output/common/mavlink_msg_camera_capture_status.h \
		include/Output/common/mavlink_msg_camera_image_captured.h \
		include/Output/common/mavlink_msg_flight_information.h \
		include/Output/common/mavlink_msg_mount_orientation.h \
		include/Output/common/mavlink_msg_logging_data.h \
		include/Output/common/mavlink_msg_logging_data_acked.h \
		include/Output/common/mavlink_msg_logging_ack.h \
		include/Output/common/mavlink_msg_video_stream_information.h \
		include/Output/common/mavlink_msg_video_stream_status.h \
		include/Output/common/mavlink_msg_camera_fov_status.h \
		include/Output/common/mavlink_msg_camera_tracking_image_status.h \
		include/Output/common/mavlink_msg_camera_tracking_geo_status.h \
		include/Output/common/mavlink_msg_camera_thermal_range.h \
		include/Output/common/mavlink_msg_gimbal_manager_information.h \
		include/Output/common/mavlink_msg_gimbal_manager_status.h \
		include/Output/common/mavlink_msg_gimbal_manager_set_attitude.h \
		include/Output/common/mavlink_msg_gimbal_device_information.h \
		include/Output/common/mavlink_msg_gimbal_device_set_attitude.h \
		include/Output/common/mavlink_msg_gimbal_device_attitude_status.h \
		include/Output/common/mavlink_msg_autopilot_state_for_gimbal_device.h \
		include/Output/common/mavlink_msg_gimbal_manager_set_pitchyaw.h \
		include/Output/common/mavlink_msg_gimbal_manager_set_manual_control.h \
		include/Output/common/mavlink_msg_esc_info.h \
		include/Output/common/mavlink_msg_esc_status.h \
		include/Output/common/mavlink_msg_wifi_config_ap.h \
		include/Output/common/mavlink_msg_ais_vessel.h \
		include/Output/common/mavlink_msg_uavcan_node_status.h \
		include/Output/common/mavlink_msg_uavcan_node_info.h \
		include/Output/common/mavlink_msg_param_ext_request_read.h \
		include/Output/common/mavlink_msg_param_ext_request_list.h \
		include/Output/common/mavlink_msg_param_ext_value.h \
		include/Output/common/mavlink_msg_param_ext_set.h \
		include/Output/common/mavlink_msg_param_ext_ack.h \
		include/Output/common/mavlink_msg_obstacle_distance.h \
		include/Output/common/mavlink_msg_odometry.h \
		include/Output/common/mavlink_msg_trajectory_representation_waypoints.h \
		include/Output/common/mavlink_msg_trajectory_representation_bezier.h \
		include/Output/common/mavlink_msg_cellular_status.h \
		include/Output/common/mavlink_msg_isbd_link_status.h \
		include/Output/common/mavlink_msg_cellular_config.h \
		include/Output/common/mavlink_msg_raw_rpm.h \
		include/Output/common/mavlink_msg_utm_global_position.h \
		include/Output/common/mavlink_msg_debug_float_array.h \
		include/Output/common/mavlink_msg_orbit_execution_status.h \
		include/Output/common/mavlink_msg_smart_battery_info.h \
		include/Output/common/mavlink_msg_fuel_status.h \
		include/Output/common/mavlink_msg_battery_info.h \
		include/Output/common/mavlink_msg_generator_status.h \
		include/Output/common/mavlink_msg_actuator_output_status.h \
		include/Output/common/mavlink_msg_time_estimate_to_target.h \
		include/Output/common/mavlink_msg_tunnel.h \
		include/Output/common/mavlink_msg_can_frame.h \
		include/Output/common/mavlink_msg_onboard_computer_status.h \
		include/Output/common/mavlink_msg_component_information.h \
		include/Output/common/mavlink_msg_component_information_basic.h \
		include/Output/common/mavlink_msg_component_metadata.h \
		include/Output/common/mavlink_msg_play_tune_v2.h \
		include/Output/common/mavlink_msg_supported_tunes.h \
		include/Output/common/mavlink_msg_event.h \
		include/Output/common/mavlink_msg_current_event_sequence.h \
		include/Output/common/mavlink_msg_request_event.h \
		include/Output/common/mavlink_msg_response_event_error.h \
		include/Output/common/mavlink_msg_available_modes.h \
		include/Output/common/mavlink_msg_current_mode.h \
		include/Output/common/mavlink_msg_available_modes_monitor.h \
		include/Output/common/mavlink_msg_illuminator_status.h \
		include/Output/common/mavlink_msg_canfd_frame.h \
		include/Output/common/mavlink_msg_can_filter_modify.h \
		include/Output/common/mavlink_msg_wheel_distance.h \
		include/Output/common/mavlink_msg_winch_status.h \
		include/Output/common/mavlink_msg_open_drone_id_basic_id.h \
		include/Output/common/mavlink_msg_open_drone_id_location.h \
		include/Output/common/mavlink_msg_open_drone_id_authentication.h \
		include/Output/common/mavlink_msg_open_drone_id_self_id.h \
		include/Output/common/mavlink_msg_open_drone_id_system.h \
		include/Output/common/mavlink_msg_open_drone_id_operator_id.h \
		include/Output/common/mavlink_msg_open_drone_id_message_pack.h \
		include/Output/common/mavlink_msg_open_drone_id_arm_status.h \
		include/Output/common/mavlink_msg_open_drone_id_system_update.h \
		include/Output/common/mavlink_msg_hygrometer_sensor.h \
		include/Output/standard/standard.h \
		include/Output/minimal/minimal.h \
		include/Output/minimal/mavlink_msg_heartbeat.h \
		include/Output/minimal/mavlink_msg_protocol_version.h \
		include/Output/mavlink_get_info.h \
		include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mavlink.o src/mavlink.cpp

navigation_unit.o: src/navigation_unit.cpp include/navigation_unit.h \
		include/mavlink.h \
		include/Output/common/mavlink.h \
		include/Output/common/version.h \
		include/Output/common/common.h \
		include/Output/protocol.h \
		include/Output/mavlink_types.h \
		include/Output/mavlink_helpers.h \
		include/Output/checksum.h \
		include/Output/mavlink_conversions.h \
		include/Output/mavlink_sha256.h \
		include/Output/common/mavlink_msg_sys_status.h \
		include/Output/common/mavlink_msg_system_time.h \
		include/Output/common/mavlink_msg_ping.h \
		include/Output/common/mavlink_msg_change_operator_control.h \
		include/Output/common/mavlink_msg_change_operator_control_ack.h \
		include/Output/common/mavlink_msg_auth_key.h \
		include/Output/common/mavlink_msg_link_node_status.h \
		include/Output/common/mavlink_msg_set_mode.h \
		include/Output/common/mavlink_msg_param_request_read.h \
		include/Output/common/mavlink_msg_param_request_list.h \
		include/Output/common/mavlink_msg_param_value.h \
		include/Output/common/mavlink_msg_param_set.h \
		include/Output/common/mavlink_msg_gps_raw_int.h \
		include/Output/common/mavlink_msg_gps_status.h \
		include/Output/common/mavlink_msg_scaled_imu.h \
		include/Output/common/mavlink_msg_raw_imu.h \
		include/Output/common/mavlink_msg_raw_pressure.h \
		include/Output/common/mavlink_msg_scaled_pressure.h \
		include/Output/common/mavlink_msg_attitude.h \
		include/Output/common/mavlink_msg_attitude_quaternion.h \
		include/Output/common/mavlink_msg_local_position_ned.h \
		include/Output/common/mavlink_msg_global_position_int.h \
		include/Output/common/mavlink_msg_rc_channels_scaled.h \
		include/Output/common/mavlink_msg_rc_channels_raw.h \
		include/Output/common/mavlink_msg_servo_output_raw.h \
		include/Output/common/mavlink_msg_mission_request_partial_list.h \
		include/Output/common/mavlink_msg_mission_write_partial_list.h \
		include/Output/common/mavlink_msg_mission_item.h \
		include/Output/common/mavlink_msg_mission_request.h \
		include/Output/common/mavlink_msg_mission_set_current.h \
		include/Output/common/mavlink_msg_mission_current.h \
		include/Output/common/mavlink_msg_mission_request_list.h \
		include/Output/common/mavlink_msg_mission_count.h \
		include/Output/common/mavlink_msg_mission_clear_all.h \
		include/Output/common/mavlink_msg_mission_item_reached.h \
		include/Output/common/mavlink_msg_mission_ack.h \
		include/Output/common/mavlink_msg_set_gps_global_origin.h \
		include/Output/common/mavlink_msg_gps_global_origin.h \
		include/Output/common/mavlink_msg_param_map_rc.h \
		include/Output/common/mavlink_msg_mission_request_int.h \
		include/Output/common/mavlink_msg_safety_set_allowed_area.h \
		include/Output/common/mavlink_msg_safety_allowed_area.h \
		include/Output/common/mavlink_msg_attitude_quaternion_cov.h \
		include/Output/common/mavlink_msg_nav_controller_output.h \
		include/Output/common/mavlink_msg_global_position_int_cov.h \
		include/Output/common/mavlink_msg_local_position_ned_cov.h \
		include/Output/common/mavlink_msg_rc_channels.h \
		include/Output/common/mavlink_msg_request_data_stream.h \
		include/Output/common/mavlink_msg_data_stream.h \
		include/Output/common/mavlink_msg_manual_control.h \
		include/Output/common/mavlink_msg_rc_channels_override.h \
		include/Output/common/mavlink_msg_mission_item_int.h \
		include/Output/common/mavlink_msg_vfr_hud.h \
		include/Output/common/mavlink_msg_command_int.h \
		include/Output/common/mavlink_msg_command_long.h \
		include/Output/common/mavlink_msg_command_ack.h \
		include/Output/common/mavlink_msg_command_cancel.h \
		include/Output/common/mavlink_msg_manual_setpoint.h \
		include/Output/common/mavlink_msg_set_attitude_target.h \
		include/Output/common/mavlink_msg_attitude_target.h \
		include/Output/common/mavlink_msg_set_position_target_local_ned.h \
		include/Output/common/mavlink_msg_position_target_local_ned.h \
		include/Output/common/mavlink_msg_set_position_target_global_int.h \
		include/Output/common/mavlink_msg_position_target_global_int.h \
		include/Output/common/mavlink_msg_local_position_ned_system_global_offset.h \
		include/Output/common/mavlink_msg_hil_state.h \
		include/Output/common/mavlink_msg_hil_controls.h \
		include/Output/common/mavlink_msg_hil_rc_inputs_raw.h \
		include/Output/common/mavlink_msg_hil_actuator_controls.h \
		include/Output/common/mavlink_msg_optical_flow.h \
		include/Output/common/mavlink_msg_global_vision_position_estimate.h \
		include/Output/common/mavlink_msg_vision_position_estimate.h \
		include/Output/common/mavlink_msg_vision_speed_estimate.h \
		include/Output/common/mavlink_msg_vicon_position_estimate.h \
		include/Output/common/mavlink_msg_highres_imu.h \
		include/Output/common/mavlink_msg_optical_flow_rad.h \
		include/Output/common/mavlink_msg_hil_sensor.h \
		include/Output/common/mavlink_msg_sim_state.h \
		include/Output/common/mavlink_msg_radio_status.h \
		include/Output/common/mavlink_msg_file_transfer_protocol.h \
		include/Output/common/mavlink_msg_timesync.h \
		include/Output/common/mavlink_msg_camera_trigger.h \
		include/Output/common/mavlink_msg_hil_gps.h \
		include/Output/common/mavlink_msg_hil_optical_flow.h \
		include/Output/common/mavlink_msg_hil_state_quaternion.h \
		include/Output/common/mavlink_msg_scaled_imu2.h \
		include/Output/common/mavlink_msg_log_request_list.h \
		include/Output/common/mavlink_msg_log_entry.h \
		include/Output/common/mavlink_msg_log_request_data.h \
		include/Output/common/mavlink_msg_log_data.h \
		include/Output/common/mavlink_msg_log_erase.h \
		include/Output/common/mavlink_msg_log_request_end.h \
		include/Output/common/mavlink_msg_gps_inject_data.h \
		include/Output/common/mavlink_msg_gps2_raw.h \
		include/Output/common/mavlink_msg_power_status.h \
		include/Output/common/mavlink_msg_serial_control.h \
		include/Output/common/mavlink_msg_gps_rtk.h \
		include/Output/common/mavlink_msg_gps2_rtk.h \
		include/Output/common/mavlink_msg_scaled_imu3.h \
		include/Output/common/mavlink_msg_data_transmission_handshake.h \
		include/Output/common/mavlink_msg_encapsulated_data.h \
		include/Output/common/mavlink_msg_distance_sensor.h \
		include/Output/common/mavlink_msg_terrain_request.h \
		include/Output/common/mavlink_msg_terrain_data.h \
		include/Output/common/mavlink_msg_terrain_check.h \
		include/Output/common/mavlink_msg_terrain_report.h \
		include/Output/common/mavlink_msg_scaled_pressure2.h \
		include/Output/common/mavlink_msg_att_pos_mocap.h \
		include/Output/common/mavlink_msg_set_actuator_control_target.h \
		include/Output/common/mavlink_msg_actuator_control_target.h \
		include/Output/common/mavlink_msg_altitude.h \
		include/Output/common/mavlink_msg_resource_request.h \
		include/Output/common/mavlink_msg_scaled_pressure3.h \
		include/Output/common/mavlink_msg_follow_target.h \
		include/Output/common/mavlink_msg_control_system_state.h \
		include/Output/common/mavlink_msg_battery_status.h \
		include/Output/common/mavlink_msg_autopilot_version.h \
		include/Output/common/mavlink_msg_landing_target.h \
		include/Output/common/mavlink_msg_fence_status.h \
		include/Output/common/mavlink_msg_mag_cal_report.h \
		include/Output/common/mavlink_msg_efi_status.h \
		include/Output/common/mavlink_msg_estimator_status.h \
		include/Output/common/mavlink_msg_wind_cov.h \
		include/Output/common/mavlink_msg_gps_input.h \
		include/Output/common/mavlink_msg_gps_rtcm_data.h \
		include/Output/common/mavlink_msg_high_latency.h \
		include/Output/common/mavlink_msg_high_latency2.h \
		include/Output/common/mavlink_msg_vibration.h \
		include/Output/common/mavlink_msg_home_position.h \
		include/Output/common/mavlink_msg_set_home_position.h \
		include/Output/common/mavlink_msg_message_interval.h \
		include/Output/common/mavlink_msg_extended_sys_state.h \
		include/Output/common/mavlink_msg_adsb_vehicle.h \
		include/Output/common/mavlink_msg_collision.h \
		include/Output/common/mavlink_msg_v2_extension.h \
		include/Output/common/mavlink_msg_memory_vect.h \
		include/Output/common/mavlink_msg_debug_vect.h \
		include/Output/common/mavlink_msg_named_value_float.h \
		include/Output/common/mavlink_msg_named_value_int.h \
		include/Output/common/mavlink_msg_statustext.h \
		include/Output/common/mavlink_msg_debug.h \
		include/Output/common/mavlink_msg_setup_signing.h \
		include/Output/common/mavlink_msg_button_change.h \
		include/Output/common/mavlink_msg_play_tune.h \
		include/Output/common/mavlink_msg_camera_information.h \
		include/Output/common/mavlink_msg_camera_settings.h \
		include/Output/common/mavlink_msg_storage_information.h \
		include/Output/common/mavlink_msg_camera_capture_status.h \
		include/Output/common/mavlink_msg_camera_image_captured.h \
		include/Output/common/mavlink_msg_flight_information.h \
		include/Output/common/mavlink_msg_mount_orientation.h \
		include/Output/common/mavlink_msg_logging_data.h \
		include/Output/common/mavlink_msg_logging_data_acked.h \
		include/Output/common/mavlink_msg_logging_ack.h \
		include/Output/common/mavlink_msg_video_stream_information.h \
		include/Output/common/mavlink_msg_video_stream_status.h \
		include/Output/common/mavlink_msg_camera_fov_status.h \
		include/Output/common/mavlink_msg_camera_tracking_image_status.h \
		include/Output/common/mavlink_msg_camera_tracking_geo_status.h \
		include/Output/common/mavlink_msg_camera_thermal_range.h \
		include/Output/common/mavlink_msg_gimbal_manager_information.h \
		include/Output/common/mavlink_msg_gimbal_manager_status.h \
		include/Output/common/mavlink_msg_gimbal_manager_set_attitude.h \
		include/Output/common/mavlink_msg_gimbal_device_information.h \
		include/Output/common/mavlink_msg_gimbal_device_set_attitude.h \
		include/Output/common/mavlink_msg_gimbal_device_attitude_status.h \
		include/Output/common/mavlink_msg_autopilot_state_for_gimbal_device.h \
		include/Output/common/mavlink_msg_gimbal_manager_set_pitchyaw.h \
		include/Output/common/mavlink_msg_gimbal_manager_set_manual_control.h \
		include/Output/common/mavlink_msg_esc_info.h \
		include/Output/common/mavlink_msg_esc_status.h \
		include/Output/common/mavlink_msg_wifi_config_ap.h \
		include/Output/common/mavlink_msg_ais_vessel.h \
		include/Output/common/mavlink_msg_uavcan_node_status.h \
		include/Output/common/mavlink_msg_uavcan_node_info.h \
		include/Output/common/mavlink_msg_param_ext_request_read.h \
		include/Output/common/mavlink_msg_param_ext_request_list.h \
		include/Output/common/mavlink_msg_param_ext_value.h \
		include/Output/common/mavlink_msg_param_ext_set.h \
		include/Output/common/mavlink_msg_param_ext_ack.h \
		include/Output/common/mavlink_msg_obstacle_distance.h \
		include/Output/common/mavlink_msg_odometry.h \
		include/Output/common/mavlink_msg_trajectory_representation_waypoints.h \
		include/Output/common/mavlink_msg_trajectory_representation_bezier.h \
		include/Output/common/mavlink_msg_cellular_status.h \
		include/Output/common/mavlink_msg_isbd_link_status.h \
		include/Output/common/mavlink_msg_cellular_config.h \
		include/Output/common/mavlink_msg_raw_rpm.h \
		include/Output/common/mavlink_msg_utm_global_position.h \
		include/Output/common/mavlink_msg_debug_float_array.h \
		include/Output/common/mavlink_msg_orbit_execution_status.h \
		include/Output/common/mavlink_msg_smart_battery_info.h \
		include/Output/common/mavlink_msg_fuel_status.h \
		include/Output/common/mavlink_msg_battery_info.h \
		include/Output/common/mavlink_msg_generator_status.h \
		include/Output/common/mavlink_msg_actuator_output_status.h \
		include/Output/common/mavlink_msg_time_estimate_to_target.h \
		include/Output/common/mavlink_msg_tunnel.h \
		include/Output/common/mavlink_msg_can_frame.h \
		include/Output/common/mavlink_msg_onboard_computer_status.h \
		include/Output/common/mavlink_msg_component_information.h \
		include/Output/common/mavlink_msg_component_information_basic.h \
		include/Output/common/mavlink_msg_component_metadata.h \
		include/Output/common/mavlink_msg_play_tune_v2.h \
		include/Output/common/mavlink_msg_supported_tunes.h \
		include/Output/common/mavlink_msg_event.h \
		include/Output/common/mavlink_msg_current_event_sequence.h \
		include/Output/common/mavlink_msg_request_event.h \
		include/Output/common/mavlink_msg_response_event_error.h \
		include/Output/common/mavlink_msg_available_modes.h \
		include/Output/common/mavlink_msg_current_mode.h \
		include/Output/common/mavlink_msg_available_modes_monitor.h \
		include/Output/common/mavlink_msg_illuminator_status.h \
		include/Output/common/mavlink_msg_canfd_frame.h \
		include/Output/common/mavlink_msg_can_filter_modify.h \
		include/Output/common/mavlink_msg_wheel_distance.h \
		include/Output/common/mavlink_msg_winch_status.h \
		include/Output/common/mavlink_msg_open_drone_id_basic_id.h \
		include/Output/common/mavlink_msg_open_drone_id_location.h \
		include/Output/common/mavlink_msg_open_drone_id_authentication.h \
		include/Output/common/mavlink_msg_open_drone_id_self_id.h \
		include/Output/common/mavlink_msg_open_drone_id_system.h \
		include/Output/common/mavlink_msg_open_drone_id_operator_id.h \
		include/Output/common/mavlink_msg_open_drone_id_message_pack.h \
		include/Output/common/mavlink_msg_open_drone_id_arm_status.h \
		include/Output/common/mavlink_msg_open_drone_id_system_update.h \
		include/Output/common/mavlink_msg_hygrometer_sensor.h \
		include/Output/standard/standard.h \
		include/Output/minimal/minimal.h \
		include/Output/minimal/mavlink_msg_heartbeat.h \
		include/Output/minimal/mavlink_msg_protocol_version.h \
		include/Output/mavlink_get_info.h \
		include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o navigation_unit.o src/navigation_unit.cpp

logger.o: src/logger.cpp include/logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o src/logger.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/ai/bin || mkdir -p $(INSTALL_ROOT)/opt/ai/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/ai/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/ai/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/ai/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ai/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

